#:kivy 2.1.0

<CalendarView>:
    MDBanner:
        id: banner
        text: []
        over_widget: root
        vertical_pad: root.main_screen.ids.top_bar.height - self.height
        type: "two-line"
        right_action: ["CLOSE", lambda bound_instance: self.hide()]

    MDScrollView:
        id: table_layout
        size_hint: (1, 1)
        do_scroll_x: False
        do_scroll_y: True
        scroll_type: ['bars', 'content']